name: release-docker

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
  build-docker-images:
    env:
      GITHUB_REPOSITORY: rafaelcalleja/udocker
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        BASE_IMAGE: [ubuntu:20.04, ubuntu:22.04, debian:bookworm, debian:bullseye ]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - name: Set env
        id: vars
        run: |
          echo "BUILD_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${BASE_IMAGE//:/-}" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        env:
          BUILD_VERSION: ${{ steps.vars.outputs.BUILD_VERSION }}
          IMAGE_TAG: ${{ steps.vars.outputs.IMAGE_TAG }}
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.GITHUB_REPOSITORY }}:${{ env.BUILD_VERSION }}-${{ env.IMAGE_TAG }}
          labels: ${{ steps.docker_meta.outputs.labels }}
